# Generated by Django 3.1.4 on 2021-04-18 11:06

from django.utils import timezone
from django.db import migrations
from django.utils.text import slugify


def forward(apps, schema_editor):
    post_cls = apps.get_model('elements', 'Post')
    page_cls = apps.get_model('pages', 'Page')

    for post in post_cls.objects.all():
        page_cls.objects.get_or_create(author=post.author, title=post.title, content=post.content, text=post.text,
                                       slug=slugify(post.title), created_at=post.created_date, edited_at=post.edit_date)


def backward(apps, schema_editor):
    post_cls = apps.get_model('elements', 'Post')
    page_cls = apps.get_model('pages', 'Page')

    for post in page_cls.objects.all():
        post_cls.objects.get_or_create(author=post.author, title=post.title, content=post.content, text=post.text,
                                       created_date=post.created_at, edit_date=post.edited_at or timezone.now())



class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            forward, backward
        )
    ]
