# Generated by Django 3.1.4 on 2021-04-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_pagehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagehistory',
            name='page_state',
            field=models.JSONField(null=True),
        ),
    ]
