# Generated by Django 3.1.8 on 2021-04-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_pagehistory_page_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='HTML meta:description attribute'),
        ),
    ]
