# Generated by Django 3.2 on 2021-05-13 16:34

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210425_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
